name: Python WASM Policy Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-wasm-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install OPA
      run: |
        curl -L -o opa https://openpolicyproject.org/downloads/latest/opa_linux_amd64
        chmod +x opa
        sudo mv opa /usr/local/bin/
        opa version
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build WASM bundle from Rego policies
      run: |
        mkdir -p build
        opa build --target wasm --entrypoint policy/github/release policies/ -o build/policy-bundle.tar.gz
        cd build
        tar -xzf policy-bundle.tar.gz
        ls -la
        
    - name: Validate Rego syntax
      run: |
        opa check policies/github-release.rego
        
    - name: Run Python validation tests
      run: |
        python scripts/validate_policy.py
        
    - name: Run comprehensive Python tests
      run: |
        python scripts/test_all_scenarios.py
        
    - name: Upload WASM artifacts
      uses: actions/upload-artifact@v3
      with:
        name: policy-wasm-bundle
        path: build/
        retention-days: 30
        
  performance-test:
    runs-on: ubuntu-latest
    needs: build-wasm-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Download WASM artifacts
      uses: actions/download-artifact@v3
      with:
        name: policy-wasm-bundle
        path: build/
        
    - name: Run performance benchmarks
      run: |
        python scripts/benchmark_policy.py
        
    - name: Generate performance report
      run: |
        python scripts/generate_report.py > performance-report.txt
        
    - name: Upload performance report
      uses: actions/upload-artifact@v3
      with:
        name: performance-report
        path: performance-report.txt
